name: Continuous deployment
on:
  workflow_run:
    workflows: [ "Continuous integration" ]
    branches: [ master ]
    types:
      - completed

jobs:
  setup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

  publish:
    name: Publish
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -o ./dist/ --verbosity normal

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: ./dist/
